namespace Mapas
{
    partial class FrmInicio
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.CboEdoInicial = new System.Windows.Forms.ComboBox();
            this.CboEdoFinal = new System.Windows.Forms.ComboBox();
            this.BtnInicia = new System.Windows.Forms.Button();
            this.BtnConfirma = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(111, 64);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(73, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Destino Inicial";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(111, 106);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(68, 13);
            this.label2.TabIndex = 1;
            this.label2.Text = "Destino Final";
            // 
            // CboEdoInicial
            // 
            this.CboEdoInicial.FormattingEnabled = true;
            this.CboEdoInicial.Items.AddRange(new object[] {
            "ACAMBARO",
            "ACAPULCO",
            "ACATLANDEJUAREZ",
            "ACATLANDEPEREZFIGUEROA",
            "ACATZINGO",
            "ACAYUCAN",
            "AGUAPRIETA",
            "AGUASCALIENTES",
            "ALAMO",
            "ALLENDE",
            "ALTOTONGA",
            "AMECA",
            "AMECAMECA",
            "AMOZOC",
            "ANGOSTURA",
            "ANIMASTRUJANO",
            "APIZACO",
            "ARMERIA",
            "ARRIAGA",
            "ATENQUIQUE",
            "ATIZAPAN",
            "ATLACOMULCO",
            "ATLIXCO",
            "AXIXINTLA",
            "BACA",
            "BANDERILLA",
            "BERMEJILLO",
            "BOTICARIA",
            "BRISENAS",
            "BUENAVISTA",
            "CABOSANLUCAS",
            "CADEREYTA",
            "CADEREYTADEJIMENEZ",
            "CAMPECHE",
            "CANADADEMORENO",
            "CANCUN",
            "CANSAHCAB",
            "CARAPAN",
            "CASTANOS",
            "CASTILLODETEAYO",
            "CD.ALTAMIRANO",
            "CD.DELCARMEN",
            "CD.GUZMAN",
            "CELAYA",
            "CELESTUN",
            "CHAMPOTON",
            "CHAPALILLA",
            "CHETUMAL",
            "CHICHIHUALCO",
            "CHICXULUBPUERTO",
            "CHIHUAHUA",
            "CHILPANCINGO",
            "CIUDADACUNA",
            "CIUDADALTAMIRANO",
            "CIUDADCAMARGO",
            "CIUDADCUAUHTEMOC",
            "CIUDADDELCARMEN",
            "CIUDADDEMEXICO",
            "CIUDADGUZMAN",
            "CIUDADINSURGENTES",
            "CIUDADJUAREZ",
            "CIUDADMANTE",
            "CIUDADMANUELDOBLADO",
            "CIUDADMENDOZA",
            "CIUDADOBREGON",
            "CIUDADSAHAGUN",
            "CIUDADVALLES",
            "CIUDADVICTORIA",
            "COATZACALCOS",
            "COATZACOALCOS",
            "COLIMA",
            "COMPOSTELA",
            "CONKAL",
            "CONTEPEC",
            "COPALILLO",
            "COPANDARO",
            "CORDOBA",
            "COSIO",
            "COSOLAPA",
            "COSOLEACAQUE",
            "CUACNOPALAN",
            "CUAUTLA",
            "CUAUTLIXCO",
            "CUERNAVACA",
            "CULIACAN",
            "DELICIAS",
            "DOLORESHIDALGO",
            "DURANGO",
            "DZILAMDEBRAVO",
            "ELCHOTE",
            "ELMONUMENTO",
            "ELPALMITO",
            "ELSAUZAL",
            "ELTRAPICHE",
            "EMILIANOZAPATA",
            "ENSENADA",
            "ESCARCEGA",
            "ESTADODEMEXICO",
            "FELIPECARRILLOPUERTO",
            "GOMEZPALACIO",
            "GUADALAJARA",
            "GUADALUPE",
            "GUADALUPEYCALVO",
            "GUANACEVI",
            "GUANAJUATO",
            "HALACHO",
            "HERMOSILLO",
            "HIDALGODELPARRAL",
            "HUAJUAPANDELEON",
            "HUAMANTLA",
            "HUASABAS",
            "HUEJUTLADEREYES",
            "HUESCALAPA",
            "HUITZO",
            "IGUALA",
            "IRAPUATO",
            "JANOS",
            "JILOTEPEC",
            "JIMENEZ",
            "JIQUILPAN",
            "JOCOTEPEC",
            "LAGOSDEMORENO",
            "LAMARQUESA",
            "LAPAZ",
            "LAPIEDAD",
            "LASIERRITA",
            "LATINAJA",
            "LAUNION",
            "LAVENTA",
            "LAVENTOSA",
            "LAZAROCARDENAS",
            "LEON",
            "LORETO",
            "LOSMOCHIS",
            "MANZANILLO",
            "MAPACHAPA",
            "MARAVATIO",
            "MARIADELATORRE",
            "MARQUELIA",
            "MARTINEZDELATORRE",
            "MASCOTA",
            "MATAMOROS",
            "MATEHUALA",
            "MAXCANU",
            "MAZATLAN",
            "MEOQUI",
            "MERIDA",
            "MEXICALI",
            "MEZQUITAL",
            "MIER",
            "MINATITLAN",
            "MOCOCHA",
            "MOCTEZUMA",
            "MONCLOVA",
            "MONTERREY",
            "MORELIA",
            "MORELOS",
            "MUNA",
            "NAUCALPANDEJUAREZ",
            "NAUTLA",
            "NOGALES",
            "NUEVACIUDADGUERRERO",
            "NUEVAITALIA",
            "NUEVOLAREDO",
            "NUEVONECAXA",
            "NUEVOPALOMAS",
            "OAXACA",
            "OCOZOCOAUTLA",
            "OJINAGA",
            "OJOSNEGROS",
            "OJUELOSDEJALISCO",
            "ORIZABA",
            "PACHUCA",
            "PALENQUE",
            "PAPANTLA",
            "PARAS",
            "PASODELTORO",
            "PATZCUARO",
            "PEROTE",
            "PIEDRASNEGRAS",
            "PLANDEARROYOS",
            "PLAYAAZUL",
            "PLAYADELCARMEN",
            "PORTEZUELO",
            "POTRERODELLLANO",
            "POXILA",
            "POZARICA",
            "PRESAAGUAMILPA",
            "PROGRESO",
            "PUEBLA",
            "PUEBLITODEALLENDE",
            "PUENTEDEIXTLA",
            "PUERTOANGEL",
            "PUERTOESCONDIDO",
            "PUERTOJUAREZ",
            "PUERTOMADERO",
            "PUERTOMEXICO",
            "PUERTOPENASCO",
            "PUERTOVALLARTA",
            "PUNTAPRIETA",
            "QUERETARO",
            "REYNOSA",
            "RIOLAGARTOS",
            "RIOVERDE",
            "SALAMANCA",
            "SALINACRUZ",
            "SALTILLO",
            "SANCRISTOBALDELASCASAS",
            "SANFELIPE",
            "SANLUISDELAPAZ",
            "SANLUISPOTOSI",
            "SANMARTINTEXMELUCAN",
            "SANPABLOAPETATITLAN",
            "SANPEDRO",
            "SANPEDRODELASCOLONIAS",
            "SANPEDROTAPANATEPEC",
            "SANTAANA",
            "SANTAANACHIAUTEMPAN",
            "SANTAROSALIA",
            "SAUCILLO",
            "SONOYTA",
            "SOTEAPAN",
            "SOTOLAMARINA",
            "TAMPICO",
            "TAPACHULA",
            "TAPANATEPEC",
            "TECATE",
            "TECOMAN",
            "TEHUACAN",
            "TEHUANTEPEC",
            "TEJOCOTAL",
            "TEMPOAL",
            "TEOTITLANDEFLORESMAGON",
            "TEPIC",
            "TEPOZTLAN",
            "TERRENATE",
            "TETELA",
            "TETIZ",
            "TEZIUTLAN",
            "TIHUATLAN",
            "TIJUANA",
            "TINGAMBATO",
            "TIZAYUCA",
            "TIZIMIN",
            "TLAHUALILO",
            "TLALCOZOTITLAN",
            "TLAPA",
            "TLAPACOYAN",
            "TLAXCALA",
            "TOLUCA",
            "TORREON",
            "TUXPAM",
            "TUXTEPEC",
            "TUXTLAGUTIERREZ",
            "UMAN",
            "URUAPAN",
            "VALLADOLID",
            "VERACRUZ",
            "VIEJAALAMO",
            "VILLAAHUMADA",
            "VILLAAVILACAMACHO",
            "VILLAHERMOSA",
            "VILLAHIDALGO",
            "VILLAUNION",
            "VISTAHERMOSA",
            "XALAPA",
            "ZACATECAS",
            "ZAMORA",
            "ZAPOTLANEJO",
            "ZIHUATANEJO",
            "ZINAPECUARO",
            "ZITACUARO",
            "ZONGOLICA"});
            this.CboEdoInicial.Location = new System.Drawing.Point(215, 56);
            this.CboEdoInicial.Name = "CboEdoInicial";
            this.CboEdoInicial.Size = new System.Drawing.Size(125, 21);
            this.CboEdoInicial.TabIndex = 2;
            this.CboEdoInicial.SelectedIndexChanged += new System.EventHandler(this.CboEdoInicial_SelectedIndexChanged);
            // 
            // CboEdoFinal
            // 
            this.CboEdoFinal.FormattingEnabled = true;
            this.CboEdoFinal.Items.AddRange(new object[] {
            "ACAMBARO",
            "ACAPULCO",
            "ACATLANDEJUAREZ",
            "ACATLANDEPEREZFIGUEROA",
            "ACATZINGO",
            "ACAYUCAN",
            "AGUAPRIETA",
            "AGUASCALIENTES",
            "ALAMO",
            "ALLENDE",
            "ALTOTONGA",
            "AMECA",
            "AMECAMECA",
            "AMOZOC",
            "ANGOSTURA",
            "ANIMASTRUJANO",
            "APIZACO",
            "ARMERIA",
            "ARRIAGA",
            "ATENQUIQUE",
            "ATIZAPAN",
            "ATLACOMULCO",
            "ATLIXCO",
            "AXIXINTLA",
            "BACA",
            "BANDERILLA",
            "BERMEJILLO",
            "BOTICARIA",
            "BRISENAS",
            "BUENAVISTA",
            "CABOSANLUCAS",
            "CADEREYTA",
            "CADEREYTADEJIMENEZ",
            "CAMPECHE",
            "CANADADEMORENO",
            "CANCUN",
            "CANSAHCAB",
            "CARAPAN",
            "CASTANOS",
            "CASTILLODETEAYO",
            "CD.ALTAMIRANO",
            "CD.DELCARMEN",
            "CD.GUZMAN",
            "CELAYA",
            "CELESTUN",
            "CHAMPOTON",
            "CHAPALILLA",
            "CHETUMAL",
            "CHICHIHUALCO",
            "CHICXULUBPUERTO",
            "CHIHUAHUA",
            "CHILPANCINGO",
            "CIUDADACUNA",
            "CIUDADALTAMIRANO",
            "CIUDADCAMARGO",
            "CIUDADCUAUHTEMOC",
            "CIUDADDELCARMEN",
            "CIUDADDEMEXICO",
            "CIUDADGUZMAN",
            "CIUDADINSURGENTES",
            "CIUDADJUAREZ",
            "CIUDADMANTE",
            "CIUDADMANUELDOBLADO",
            "CIUDADMENDOZA",
            "CIUDADOBREGON",
            "CIUDADSAHAGUN",
            "CIUDADVALLES",
            "CIUDADVICTORIA",
            "COATZACALCOS",
            "COATZACOALCOS",
            "COLIMA",
            "COMPOSTELA",
            "CONKAL",
            "CONTEPEC",
            "COPALILLO",
            "COPANDARO",
            "CORDOBA",
            "COSIO",
            "COSOLAPA",
            "COSOLEACAQUE",
            "CUACNOPALAN",
            "CUAUTLA",
            "CUAUTLIXCO",
            "CUERNAVACA",
            "CULIACAN",
            "DELICIAS",
            "DOLORESHIDALGO",
            "DURANGO",
            "DZILAMDEBRAVO",
            "ELCHOTE",
            "ELMONUMENTO",
            "ELPALMITO",
            "ELSAUZAL",
            "ELTRAPICHE",
            "EMILIANOZAPATA",
            "ENSENADA",
            "ESCARCEGA",
            "ESTADODEMEXICO",
            "FELIPECARRILLOPUERTO",
            "GOMEZPALACIO",
            "GUADALAJARA",
            "GUADALUPE",
            "GUADALUPEYCALVO",
            "GUANACEVI",
            "GUANAJUATO",
            "HALACHO",
            "HERMOSILLO",
            "HIDALGODELPARRAL",
            "HUAJUAPANDELEON",
            "HUAMANTLA",
            "HUASABAS",
            "HUEJUTLADEREYES",
            "HUESCALAPA",
            "HUITZO",
            "IGUALA",
            "IRAPUATO",
            "JANOS",
            "JILOTEPEC",
            "JIMENEZ",
            "JIQUILPAN",
            "JOCOTEPEC",
            "LAGOSDEMORENO",
            "LAMARQUESA",
            "LAPAZ",
            "LAPIEDAD",
            "LASIERRITA",
            "LATINAJA",
            "LAUNION",
            "LAVENTA",
            "LAVENTOSA",
            "LAZAROCARDENAS",
            "LEON",
            "LORETO",
            "LOSMOCHIS",
            "MANZANILLO",
            "MAPACHAPA",
            "MARAVATIO",
            "MARIADELATORRE",
            "MARQUELIA",
            "MARTINEZDELATORRE",
            "MASCOTA",
            "MATAMOROS",
            "MATEHUALA",
            "MAXCANU",
            "MAZATLAN",
            "MEOQUI",
            "MERIDA",
            "MEXICALI",
            "MEZQUITAL",
            "MIER",
            "MINATITLAN",
            "MOCOCHA",
            "MOCTEZUMA",
            "MONCLOVA",
            "MONTERREY",
            "MORELIA",
            "MORELOS",
            "MUNA",
            "NAUCALPANDEJUAREZ",
            "NAUTLA",
            "NOGALES",
            "NUEVACIUDADGUERRERO",
            "NUEVAITALIA",
            "NUEVOLAREDO",
            "NUEVONECAXA",
            "NUEVOPALOMAS",
            "OAXACA",
            "OCOZOCOAUTLA",
            "OJINAGA",
            "OJOSNEGROS",
            "OJUELOSDEJALISCO",
            "ORIZABA",
            "PACHUCA",
            "PALENQUE",
            "PAPANTLA",
            "PARAS",
            "PASODELTORO",
            "PATZCUARO",
            "PEROTE",
            "PIEDRASNEGRAS",
            "PLANDEARROYOS",
            "PLAYAAZUL",
            "PLAYADELCARMEN",
            "PORTEZUELO",
            "POTRERODELLLANO",
            "POXILA",
            "POZARICA",
            "PRESAAGUAMILPA",
            "PROGRESO",
            "PUEBLA",
            "PUEBLITODEALLENDE",
            "PUENTEDEIXTLA",
            "PUERTOANGEL",
            "PUERTOESCONDIDO",
            "PUERTOJUAREZ",
            "PUERTOMADERO",
            "PUERTOMEXICO",
            "PUERTOPENASCO",
            "PUERTOVALLARTA",
            "PUNTAPRIETA",
            "QUERETARO",
            "REYNOSA",
            "RIOLAGARTOS",
            "RIOVERDE",
            "SALAMANCA",
            "SALINACRUZ",
            "SALTILLO",
            "SANCRISTOBALDELASCASAS",
            "SANFELIPE",
            "SANLUISDELAPAZ",
            "SANLUISPOTOSI",
            "SANMARTINTEXMELUCAN",
            "SANPABLOAPETATITLAN",
            "SANPEDRO",
            "SANPEDRODELASCOLONIAS",
            "SANPEDROTAPANATEPEC",
            "SANTAANA",
            "SANTAANACHIAUTEMPAN",
            "SANTAROSALIA",
            "SAUCILLO",
            "SONOYTA",
            "SOTEAPAN",
            "SOTOLAMARINA",
            "TAMPICO",
            "TAPACHULA",
            "TAPANATEPEC",
            "TECATE",
            "TECOMAN",
            "TEHUACAN",
            "TEHUANTEPEC",
            "TEJOCOTAL",
            "TEMPOAL",
            "TEOTITLANDEFLORESMAGON",
            "TEPIC",
            "TEPOZTLAN",
            "TERRENATE",
            "TETELA",
            "TETIZ",
            "TEZIUTLAN",
            "TIHUATLAN",
            "TIJUANA",
            "TINGAMBATO",
            "TIZAYUCA",
            "TIZIMIN",
            "TLAHUALILO",
            "TLALCOZOTITLAN",
            "TLAPA",
            "TLAPACOYAN",
            "TLAXCALA",
            "TOLUCA",
            "TORREON",
            "TUXPAM",
            "TUXTEPEC",
            "TUXTLAGUTIERREZ",
            "UMAN",
            "URUAPAN",
            "VALLADOLID",
            "VERACRUZ",
            "VIEJAALAMO",
            "VILLAAHUMADA",
            "VILLAAVILACAMACHO",
            "VILLAHERMOSA",
            "VILLAHIDALGO",
            "VILLAUNION",
            "VISTAHERMOSA",
            "XALAPA",
            "ZACATECAS",
            "ZAMORA",
            "ZAPOTLANEJO",
            "ZIHUATANEJO",
            "ZINAPECUARO",
            "ZITACUARO",
            "ZONGOLICA"});
            this.CboEdoFinal.Location = new System.Drawing.Point(215, 98);
            this.CboEdoFinal.Name = "CboEdoFinal";
            this.CboEdoFinal.Size = new System.Drawing.Size(124, 21);
            this.CboEdoFinal.TabIndex = 3;
            // 
            // BtnInicia
            // 
            this.BtnInicia.Location = new System.Drawing.Point(338, 141);
            this.BtnInicia.Name = "BtnInicia";
            this.BtnInicia.Size = new System.Drawing.Size(162, 40);
            this.BtnInicia.TabIndex = 4;
            this.BtnInicia.Text = "Abre Mapa";
            this.BtnInicia.UseVisualStyleBackColor = true;
            this.BtnInicia.Click += new System.EventHandler(this.BtnInicia_Click);
            // 
            // BtnConfirma
            // 
            this.BtnConfirma.Location = new System.Drawing.Point(183, 141);
            this.BtnConfirma.Name = "BtnConfirma";
            this.BtnConfirma.Size = new System.Drawing.Size(121, 41);
            this.BtnConfirma.TabIndex = 5;
            this.BtnConfirma.Text = "Confirma Destinos";
            this.BtnConfirma.UseVisualStyleBackColor = true;
            this.BtnConfirma.Click += new System.EventHandler(this.BtnConfirma_Click);
            // Llama LISP dentro del botón confima 

            //
            // FrmInicio
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(549, 262);
            this.Controls.Add(this.BtnConfirma);
            this.Controls.Add(this.BtnInicia);
            this.Controls.Add(this.CboEdoFinal);
            this.Controls.Add(this.CboEdoInicial);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Name = "FrmInicio";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.FrmInicio_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.ComboBox CboEdoInicial;
        private System.Windows.Forms.ComboBox CboEdoFinal;
        private System.Windows.Forms.Button BtnInicia;
        private System.Windows.Forms.Button BtnConfirma;
    }
}